export interface Product {
  id: number
  name: string
  brand: string
  price: number
  originalPrice?: number
  rating: number
  reviewCount: number
  image: string
  category: string
  badge?: string
  inStock: boolean
}

export interface Category {
  id: string
  name: string
  icon: string
  subcategories: string[]
}

export const categories: Category[] = [
  {
    id: "skincare",
    name: "Skincare",
    icon: "sparkles",
    subcategories: [
      "Cleansers",
      "Toners",
      "Serums",
      "Moisturizers",
      "Eye Care",
      "Face Masks",
      "Exfoliants",
    ],
  },
  {
    id: "haircare",
    name: "Haircare",
    icon: "droplets",
    subcategories: [
      "Shampoos",
      "Conditioners",
      "Hair Masks",
      "Scalp Care",
      "Hair Serums",
    ],
  },
  {
    id: "bodycare",
    name: "Body Care",
    icon: "heart",
    subcategories: [
      "Body Lotions",
      "Body Wash",
      "Scrubs",
      "Deodorants",
      "Hand Cream",
    ],
  },
  {
    id: "sunprotection",
    name: "Sun Protection",
    icon: "sun",
    subcategories: [
      "SPF 50+",
      "SPF 30",
      "After Sun",
      "Self-Tanning",
      "Kids Sun Care",
    ],
  },
  {
    id: "makeup",
    name: "Makeup",
    icon: "paintbrush",
    subcategories: [
      "Foundation",
      "Lip Care",
      "Eye Makeup",
      "Blush & Bronzer",
      "Setting Sprays",
    ],
  },
  {
    id: "mencare",
    name: "Men Care",
    icon: "user",
    subcategories: [
      "Face Wash",
      "Shaving",
      "Moisturizers",
      "After Shave",
      "Body Care",
    ],
  },
  {
    id: "babymom",
    name: "Baby & Mom",
    icon: "baby",
    subcategories: [
      "Baby Skincare",
      "Baby Bath",
      "Maternity Care",
      "Diaper Care",
      "Baby Sun Protection",
    ],
  },
  {
    id: "brands",
    name: "Brands",
    icon: "tag",
    subcategories: [
      "Bioderma",
      "Vichy",
      "Avène",
      "Nuxe",
      "Biotherm",
      "Clinique",
      "Evian",
    ],
  },
]

export const products: Product[] = [
  {
    id: 1,
    name: "Sensibio H2O Micellar Water 500ml",
    brand: "Bioderma",
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.9,
    reviewCount: 24560,
    image: "/images/products/bioderma-sensibio.jpg",
    category: "skincare",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: 2,
    name: "Thermal Spring Water Spray 300ml",
    brand: "Avène",
    price: 12.50,
    rating: 4.8,
    reviewCount: 18340,
    image: "/images/products/avene-thermal.jpg",
    category: "skincare",
    badge: "Popular",
    inStock: true,
  },
  {
    id: 3,
    name: "Mineral 89 Hyaluronic Acid Serum 50ml",
    brand: "Vichy",
    price: 29.95,
    originalPrice: 37.00,
    rating: 4.8,
    reviewCount: 15890,
    image: "/images/products/vichy-mineral89.jpg",
    category: "skincare",
    badge: "Top Rated",
    inStock: true,
  },
  {
    id: 4,
    name: "Proactive Anti-Aging Serum 30ml",
    brand: "Biotherm",
    price: 49.00,
    originalPrice: 62.00,
    rating: 4.7,
    reviewCount: 9210,
    image: "/images/products/biotherm-serum.jpg",
    category: "skincare",
    badge: "21% Off",
    inStock: true,
  },
  {
    id: 5,
    name: "Moisture Surge 100H Moisturizer 50ml",
    brand: "Clinique",
    price: 42.00,
    rating: 4.6,
    reviewCount: 11450,
    image: "/images/products/clinique-moisture.jpg",
    category: "skincare",
    inStock: true,
  },
  {
    id: 6,
    name: "Huile Prodigieuse Dry Oil 100ml",
    brand: "Nuxe",
    price: 34.95,
    originalPrice: 42.00,
    rating: 4.9,
    reviewCount: 20130,
    image: "/images/products/nuxe-huile.jpg",
    category: "bodycare",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: 7,
    name: "Reve de Miel Lip Balm 15g",
    brand: "Nuxe",
    price: 9.99,
    rating: 4.8,
    reviewCount: 31200,
    image: "/images/products/nuxe-lip-balm.jpg",
    category: "makeup",
    badge: "Trending",
    inStock: true,
  },
  {
    id: 8,
    name: "Capital Soleil SPF 50+ Face Fluid 40ml",
    brand: "Vichy",
    price: 22.50,
    rating: 4.7,
    reviewCount: 8760,
    image: "/images/products/vichy-sunscreen.jpg",
    category: "sunprotection",
    inStock: true,
  },
  {
    id: 9,
    name: "Sensibio Light Soothing Cream 40ml",
    brand: "Bioderma",
    price: 21.99,
    originalPrice: 27.00,
    rating: 4.7,
    reviewCount: 7430,
    image: "/images/products/bioderma-sensibio-cream.jpg",
    category: "skincare",
    badge: "19% Off",
    inStock: true,
  },
  {
    id: 10,
    name: "Thermal Spring Water Facial Mist 50ml",
    brand: "Evian",
    price: 8.99,
    rating: 4.5,
    reviewCount: 14200,
    image: "/images/products/evian-spray.jpg",
    category: "skincare",
    inStock: true,
  },
  {
    id: 11,
    name: "Life Plankton Essence 175ml",
    brand: "Biotherm",
    price: 68.00,
    originalPrice: 82.00,
    rating: 4.8,
    reviewCount: 6540,
    image: "/images/products/biotherm-essence.jpg",
    category: "skincare",
    badge: "17% Off",
    inStock: true,
  },
  {
    id: 12,
    name: "Eau Thermale Gentle Cleansing Gel 200ml",
    brand: "Avène",
    price: 14.95,
    rating: 4.6,
    reviewCount: 9870,
    image: "/images/products/avene-cleansing.jpg",
    category: "skincare",
    inStock: true,
  },
  {
    id: 13,
    name: "Dercos Anti-Dandruff Shampoo 200ml",
    brand: "Vichy",
    price: 17.50,
    originalPrice: 22.00,
    rating: 4.6,
    reviewCount: 12300,
    image: "/images/products/vichy-shampoo.jpg",
    category: "haircare",
    badge: "Sale",
    inStock: true,
  },
  {
    id: 14,
    name: "Aquasource Gel Moisturizer 50ml",
    brand: "Biotherm",
    price: 39.00,
    rating: 4.5,
    reviewCount: 5670,
    image: "/images/products/biotherm-aquasource.jpg",
    category: "skincare",
    inStock: true,
  },
  {
    id: 15,
    name: "Atoderm Intensive Baume 500ml",
    brand: "Bioderma",
    price: 26.99,
    originalPrice: 33.00,
    rating: 4.8,
    reviewCount: 10890,
    image: "/images/products/bioderma-atoderm.jpg",
    category: "bodycare",
    badge: "Popular",
    inStock: true,
  },
  {
    id: 16,
    name: "Dramatically Different Moisturizing Lotion 125ml",
    brand: "Clinique",
    price: 35.00,
    rating: 4.7,
    reviewCount: 17650,
    image: "/images/products/clinique-ddml.jpg",
    category: "skincare",
    inStock: true,
  },
]

export const promoBarItems = [
  "Бесплатная доставка по Латвии при заказе от 40€",
  "Скидка 15% на первый заказ с кодом PHARMIPERIA15",
  "Новинки Bioderma, Vichy и Avène уже в наличии",
]
